### ISSUE TITLE
Whitespace in light metadata file

### ISSUE THREAD

**Issue by amagidow** [OpenITI/Annotation#1]
Some kind of bug is producing whitespace in the OpenITI_metadata_light.csv file. This means that the URI's are incorrect, and so software based on those will fail to find the file. 
For example, from the URI field (but see also the versionURI field):
https://raw.githubusercontent.com/OpenITI/0125AH/master/data/0110IbnSirin/0110IbnSirin.MuntakhabKalamFiTafsirAhlam /0110IbnSirin.MuntakhabKalamFiTafsirAhlam .Shia004640Vols-ara1

**Comment by maximromanov** [comment]
Should be fixed now.
