### ISSUE TITLE
mukharrij: 0766IbnIbrahimIbnImamSakhra.Mashyakha

### ISSUE THREAD

**Issue by Lrnzmtths** [OpenITI/Annotation#1161]
Different URIs for the same text:

0766IbnIbrahimIbnImamSakhra.Mashyakha 
0774IbnRaficSallami.MashyakhatBayani 

NB: 0774IbnRafic is the mukharrij.

**Comment by pverkind** [comment]
Changed URI: 0766IbnIbrahimIbnImamSakhra.Mashyakha > 0774IbnRaficSallami.MashyakhatBayani
