### ISSUE TITLE
Text tagged: 0779IbnBattuta.Rihla.Shamela0011769-ara1 (in progress: pushed for corpus update)

### ISSUE THREAD

**Issue by Simonpeterloynes** [OpenITI/Annotation#1266]
00#VERS#CLENGTH##: 1065374
00#VERS#LENGTH###: 243197
00#VERS#URI######: 0779IbnBattuta.Rihla.Shamela0011769-ara1
80#VERS#BASED####: http://www.worldcat.org/oclc/236017736
80#VERS#COLLATED#: http://www.worldcat.org/oclc/236017736
80#VERS#LINKS####: https://books-library.online/free-568764757-download (1), https://books-library.online/free-542084129-download (2), https://books-library.online/free-474561713-download (3), https://books-library.online/free-475865041-download (4), https://books-library.online/free-482406745-download (5)
90#VERS#ANNOTATOR: SP Loynes
90#VERS#COMMENT##: Partially annotated - pushed for corpus update.
90#VERS#DATE#####: YYYY-MM-DD
90#VERS#ISSUES###: formalized issues, separated with commas

**Comment by pverkind** [comment]
now fully finished: see #1277
