### ISSUE TITLE
Broken link on project main pae

### ISSUE THREAD

**Issue by tomersagi** [OpenITI/Annotation#1446]
Hi!
I'm a fan of your work. 
Notice that there is a link on this page: http://kitab-project.org/openiti/ to http://iti-corpus.github.io/  which does not exist. 
Please fix to refer to the actual project description. 
Thanks
Tomer

**Comment by sohailmerchant** [comment]
@tomersagi thank you for reporting this.  I have now updated the link with the new website for OpenITI project.
