### ISSUE TITLE
Duplicate Texts Issue

### ISSUE THREAD

**Issue by maximromanov** [OpenITI/Annotation#16]
1. Some of the same texts got assigned different URIs.
2. To fix: analyze metadata > URIs are different, but IDs are the same;
3. That is: find all items in metadata that have the same IDs, but different URIs
4. Check manually
5. Fix URIs (submit via issues)

**Comment by pverkind** [comment]
Done. No more duplicate IDs in the corpus (except some files that have .inProgress and no extension version)
