### ISSUE TITLE
REDUNDANT TEXT: 0543IbnHusaynBaquliIsbahani.IcrabQuran.JK011943-ara1

### ISSUE THREAD

**Issue by hamidrh66** [OpenITI/Annotation#1617]
JK011943 seems to be unrelated to Baquli’s I’rab Quran. It seems to be a modern text about the Quran and its role in Islamic societies. I couldn’t find it on the internet and it’s strange that it is in this folder. Most probably it must be deleted from the corpus. Baquli’s I’rab Quran has been tagged: https://github.com/OpenITI/Annotation/issues/1615
See also: https://github.com/OpenITI/Annotation/issues/1616

**Comment by pverkind** [comment]
It seems to be this book: https://al-maktaba.org/book/11089: كتاب تدريس القرآن الكريم في السجون ودور الملاحظة الاجتماعية

**Comment by pverkind** [comment]
Removed this file.
