### ISSUE TITLE
MISSING TEXT: 1376CabdRahmanSacdi.Muallafat.JK010075-ara1

### ISSUE THREAD

**Issue by hamidrh66** [OpenITI/Annotation#1618]
As I pointed out in another issue (https://github.com/OpenITI/Annotation/issues/1616), this text is actually 0543IbnHusaynBaquliIsbahani.IcrabQuran and should be transferred to its folder. Since this is the only version of the text in this folder, it means that ‘Abd al-Rahman Sa’di’s Muallafat does not exist in the corpus and must be added. Find the PDF of this huge text (81 volumes) here: https://archive.org/details/Moallafat_Ashaikh_Allamah_Assa3di/00.0%20-%20%D8%A7%D9%84%D8%BA%D9%84%D8%A7%D9%81

**Comment by pverkind** [comment]
Changed URI: 1376CabdRahmanSacdi.Muallafat.JK010075-ara1 > 0543IbnHusaynBaquliIsbahani.IcrabQuran.JK010075-ara1
