### ISSUE TITLE
MORE THAN ONE TEXT: 0968Tashkubruizadah.ShaqaiqNucmaniyya.Shamela0006723-ara1.completed

### ISSUE THREAD

**Issue by Simonpeterloynes** [OpenITI/Annotation#1730]
Appended to the end is another book by the same author 'العقد المنظوم في ذكر افاضل الروم', which should be separated (it is tagged).

**Comment by pverkind** [comment]
Split the file into two files: 
0968Tashkubruizadah.ShaqaiqNucmaniyya.Shamela0006723BK1-ara1
0968Tashkuprizadah.CiqdManzum.Shamela0006723BK2-ara1
