### ISSUE TITLE
MORE THAN ONE TEXT: 0279Tirmidhi.JamicSahih.Shamela0000782-ara1

### ISSUE THREAD

**Issue by Maroussia** [OpenITI/Annotation#1827]
This text contains the Jami'/Sunan of Tirmidhi, and the comments of al-Albani (as stated in the metadata). If it remains in the folder of Tirmidh's Jami' it should probably be classified as a commentary and one might want to check whether the content of this commentary is the same as the non-commented versions.

**Comment by pverkind** [comment]
Changed URI: 0279Tirmidhi.JamicSahih.Shamela0000782-ara1 > 1420MuhammadNasirDinAlbani.SahihWaDacifSunanTirmidhi
