### ISSUE TITLE
MORE THAN ONE TEXT: 0255Jahiz.Cuthmaniya.Shia003459-ara1

### ISSUE THREAD

**Issue by Simonpeterloynes** [OpenITI/Annotation#1902]
There is another text included: مناقضات أبى جعفر الإسكافي لبعض ما أورده الجاحظ في العثمانية من شرح نهج البلاغة لابن أبي الحديد

NOTE: Please, paste the URI of the text into the header.

**Comment by pverkind** [comment]
I split the text file into two: 
0255Jahiz.Cuthmaniya.Shia003459BK1-ara1
0220AbuJacfarIskafi.NaqdCuthmaniyya.Shia003459BK2-ara1 (currently in barzakh)
