### ISSUE TITLE
Missing diacritics in files

### ISSUE THREAD

**Issue by Kentoseth** [OpenITI/Annotation#1992]
**LINK:** 0179MalikIbnAnas.Muwatta & 0195MuarrijSadusi.HadhfMinNasabQuraysh

**ISSUE:** I did a rough analysis of the corpus data by looking at `.completed` files from Shamela. In the above 2 examples, the contents in your files have stripped away all the diacritics/tashkeel/harakat but in the available versions on Shamela, the diacritics are present in their ePub releases:

Shamela Link: [Muwatta](https://shamela.ws/index.php/book/1699)

The value of the diacritics is immense for all types of computational analysis.

I believe this problem might extend to every Shamela book you have(some contain diacritics and some don't but it appears that your processing method has stripped it away in all the books).

**RESOLUTION:** The work on the Shamela books might need to be redone to include the diacritics.

**QUESTION:** Do you have the raw data for the JK collection? I would like to compare if the diacritics are missing from those too. My assumption is that the raw JK collection might also have the original diacritics in some of the books.

**Comment by Lrnzmtths** [comment]
We remove diacritics in a separate normalisation step during our computational analysis of text reuse. Accordingly, their presence or absence in a given text is not really relevant for us. 

NB: Regarding the ePub releases, not all of them are contain all diacritics.

**Comment by Kentoseth** [comment]
> Accordingly, their presence or absence in a given text is not really relevant for us.

Why? 

Doesn't the usage(even in computational analysis and on partial diacritics) help remove ambiguity from the text meaning?

> Regarding the ePub releases, not all of them are contain all diacritics.

That's correct, but many have partial diacritics in them.
