### ISSUE TITLE
1014IbnSultanHarawi

### ISSUE THREAD

**Issue by IKFKirchner** [OpenITI/Annotation#2121]
**OLD URI:** 1014IbnSultanHarawi
**NEW URI:** 1014AliAlQari
**REASON:** This famous Islamic scholar is commonly known as (Mullah) Ali Al-Qari. 

**NOTE:** Please, paste the *old* URI into the header. If you think the death date or the author's name should be changed in all URIs of that author, please fill in the author URI only (e.g., 0255Jahiz). If you think something needs to change in the title of a book, in all versions, please fill in the book URI only (e.g., 0255Jahiz.Hayawan). Finally, if a URI change relates only to a specific version of the book, fill in the Version URI (e.g., 0255Jahiz.Hayawan.Shamela0000001-ara1).

**Comment by pverkind** [comment]
Thanks! This will be changed today in preparation for the new release, to 1014MullaCaliQari (we drop the article al- in our URIs, and use C for ع)

**Comment by pverkind** [comment]
URI changed: 1014IbnSultanHarawi > 1014MullaCaliQari
