### ISSUE TITLE
DISCREPANCIES: 0255CabdAllahDarimi

### ISSUE THREAD

**Issue by Maroussia** [OpenITI/Annotation#2232]
ID: 0255CabdAllahDarimi.Musnad
ID: 0255CabdAllahDarimi.Sunan

Issue: These are probably several versions of the same text. Al-Darimi's Sunan is often called 'Musnad' and sometimes 'Jami''. There are many versions in each folder, it might be worth checking how they differ from each other and potentially gather them in one folder [ideally called Sunan, this is how the text is usually referred to] if indeed they all come from one source. This version for instance Shamela_0021795 is called 
"مسند الدارمي المعروف بـ (سنن الدارمي)" and it is located in the 'Sunan' folder.

**Comment by pverkind** [comment]
Thanks for this, Maroussia! I think you're right, I'll do this soon.

**Comment by pverkind** [comment]
Update: The "Musnad" versions will be renamed to "Sunan" for the next release

**Comment by pverkind** [comment]
URI changed: 0255CabdAllahDarimi.Musnad > 0255CabdAllahDarimi.Sunan

**Comment by Maroussia** [comment]
Thank You so much @pverkind ! It's really great to see so much progress on OpenITI's quality thanks to your dedicated work!
