### ISSUE TITLE
0306IbnHayyanDabbi

### ISSUE THREAD

**Issue by intisarrabb** [OpenITI/Annotation#2283]
**OLD URI:** 0306IbnHayyanDabbi
**NEW URI:** 0306Wakic
**REASON:** This author is far  more popularly known as Wakī‛ with the full or alternative name as Muḥammad b. Khalaf b. Ḥayyān; but virtually no scholar refers to him as Ibn Ḥayyān [al-Dabbi]. The name difference makes it difficult to search for the work by this known author by his common name. This would apply to all of the works by Waki' [currently listed as IbnHayyanDabbi].

**NOTE:** Please, paste the *old* URI into the header. If you think the death date or the author's name should be changed in all URIs of that author, please fill in the author URI only (e.g., 0255Jahiz). If you think something needs to change in the title of a book, in all versions, please fill in the book URI only (e.g., 0255Jahiz.Hayawan). Finally, if a URI change relates only to a specific version of the book, fill in the Version URI (e.g., 0255Jahiz.Hayawan.Shamela0000001-ara1).

**Comment by pverkind** [comment]
Thanks, Intisar, this will be changed for the next release!

**Comment by pverkind** [comment]
Done: URI changed 0306IbnHayyanDabbi > 0306Wakic
