### ISSUE TITLE
1150IbnCaqila.FawaidJlalila - typo

### ISSUE THREAD

**Issue by maximromanov** [OpenITI/Annotation#2841]
**OLD URI:** 1150IbnCaqila.FawaidJlalila
**NEW URI:** 1150IbnCaqila.FawaidJalila
**REASON:** typo in the title of the work

**Comment by pverkind** [comment]
Changed URI: 1150IbnCaqila.FawaidJlalila > 1150IbnCaqila.FawaidJalila
