### ISSUE TITLE
PARTIAL TEXT: 0774IbnKathir.Bidaya

### ISSUE THREAD

**Issue by hamidrh66** [OpenITI/Annotation#290]
Shamela0004445: complete edition, tagged
Shamela0023678: a section ("معجزات النبي"), not tagged
Shamela0000930: a section ("سيرة النبي"), not tagged
JK010930: a section ("سيرة النبي"), not tagged
Shia003717Vols: a section ("سيرة النبي"), not tagged

**Comment by pverkind** [comment]
See the 0774IbnKathir.Bidaya.yml file for full info on the different versions in the corpus
