### ISSUE TITLE
Incorrect author and date attributions

### ISSUE THREAD

**Issue by amagidow** [OpenITI/Annotation#3]
The following files are incorrectly marked in Shamela. They are modern sharH based on premodern texts, but Shamela lists them by the original author, including the DOD of that author. In reality, they contain extensive explanations surrounding the original texts and should not be listed as being the texts by the original author. 

The correct author is CabdAlKariimKhaDiir (http://shamela.ws/index.php/author/1156), DOB 1955, still living. 

These are the files in the Shamela repository, many are still in openITI:
Shamela0006366
Shamela0012399
Shamela0012878
Shamela0021509
Shamela0021627
Shamela0021700
Shamela0021709
Shamela0021724
Shamela0021741
Shamela0021803
Shamela0022644
Shamela0022645
Shamela0023349
Shamela0023361
Shamela0023405
Shamela0023408
Shamela0023422
Shamela0023423
Shamela0023424
Shamela0023737
Shamela0023743
Shamela0023745
Shamela0023757
Shamela0023765
Shamela0023769
Shamela0023774
Shamela0023777
Shamela0023834
Shamela0023839
Shamela0023842
Shamela0025814
Shamela0025851
Shamela0025863
Shamela0025955
Shamela0025976
Shamela0026047
Shamela0026252
Shamela0026302
Shamela0027194
Shamela0027247
Shamela0027248
Shamela0027254

**Comment by pverkind** [comment]
Closing this issue; I made separate URI change request issues for the remaining problems.
