### ISSUE TITLE
Candidate to be added to the Corpus: Anonymous.MukhtasarSiyaq

### ISSUE THREAD

**Issue by hamidrh66** [OpenITI/Annotation#3079]
‘Abd al-Ghafir al-Farisi has a book entitled ‘al-Siyaq li-tarikh Naysabur’, which is lost, but two selections from this text have remained. One of them is is collected by Sarifini and we have it in the corpus (0641Sarifini.Muntakhab), and the other one is collected by an anonymous writer and should be added to the corpus. It is available here: https://shamela.ws/book/1080

**Comment by pverkind** [comment]
The text is now in Barzakh! Proposed URI: 0600Anonymous.MukhtasarSiyaq

**Comment by pverkind** [comment]
The text is now in Barzakh! Proposed URI: 0600Anonymous.MukhtasarSiyaq

**Comment by pverkind** [comment]
now in the corpus
