### ISSUE TITLE
TEXTS GOT MESSED UP

### ISSUE THREAD

**Issue by maximromanov** [OpenITI/Annotation#308]
The following texts must be cleaned: edits merged with unedited chunks. Those are marked with `<<<<<<< HEAD`, splitting with `=======`, and ending with `>>>>>>>` and a hash. 

0764Safadi.WafiBiWafayat.JK003609-ara1.completed
0764Safadi.AcyanCasr.Shamela0000131-ara1.completed

**Comment by maximromanov** [comment]
Other texts:

0310Tabari.Tarikh.Shia003474Vols-ara1.inProgress
0310Tabari.Tarikh.SBS20191023-ara1.inProgress

**Comment by pverkind** [comment]
Solved
