### ISSUE TITLE
CHANGE URI: 0800IbnCadilHanbali > 0880IbnCadilHanbali

### ISSUE THREAD

**Issue by maximromanov** [OpenITI/Annotation#3092]
**OLD URI:** 0800IbnCadilHanbali
**NEW URI:** 0880IbnCadilHanbali
**REASON:** The date is given as 880 in most cases.

**NOTE:** <https://ar.wikipedia.org/wiki/%D8%A7%D9%84%D9%84%D8%A8%D8%A7%D8%A8_%D9%81%D9%8A_%D8%B9%D9%84%D9%88%D9%85_%D8%A7%D9%84%D9%83%D8%AA%D8%A7%D8%A8>; 
<https://ar.wikipedia.org/wiki/%D8%A7%D8%A8%D9%86_%D8%B9%D8%A7%D8%AF%D9%84_%D8%A7%D9%84%D8%AD%D9%86%D8%A8%D9%84%D9%8A>

**Comment by pverkind** [comment]
Changed URI: 0800IbnCadilHanbali > 0880IbnCadilHanbali
