### ISSUE TITLE
0353MaslamaQurtubi.GhayatHakim.Noorlib018390-ara1

### ISSUE THREAD

**Issue by letiziaosti** [OpenITI/Annotation#3175]
**PRI:** please, paste the full URI of the text that should be considered PRImary
**RESOLUTION:** Please, propose what should be done with the text

**NOTE:** Please, paste the URI of the text into the header.

**Comment by pverkind** [comment]
(closing this issue after contacting Letizia - the issue was not so much a PRI & SEC issue but rather that the text was not available through the metadata app - since it is in the folder for copyrighted works)
