### ISSUE TITLE
0145MufaddalIbnCumarJucfi.KitabHaftWaAzilla.Noorlib0015842-ara1

### ISSUE THREAD

**Issue by AndrewSutherl** [OpenITI/Annotation#3399]
The link to the text leads to a "404 error" page.

Could this be changed in anyway in the near futur ? could it be possible to have access to the raw data though another channel ?

Thank you for your time.

Best wishes,

Andrew Sutherland
Masters student, Faculty of Arts, University of Lausanne

**Comment by maximromanov** [comment]
This text is not available in the open corpus
