### ISSUE TITLE
0281IbnAbiDunya.HammWaHuzn.JK000016-ara1

### ISSUE THREAD

**Issue by mzeidhassan** [OpenITI/Annotation#411]
**OLD URI:** [old URI](https://raw.githubusercontent.com/OpenITI/0300AH/master/data/0281IbnAbiDunya/0281IbnAbiDunya.HammWaHuzn/0281IbnAbiDunya.HammWaHuzn.JK000016-ara1).
**NEW URI:** n/a.
**REASON:** Please, provide reasons why the URI should be corrected.

I checked a couple of books, and they all return 404 error:

`404: Not Found`

Thanks

**Comment by mzeidhassan** [comment]
This should have "no edition found" label. but I am not able to change it. Sorry!

**Comment by hamidrh66** [comment]
I have tagged this text a few month ago:
https://github.com/OpenITI/Annotation/issues/154
