### ISSUE TITLE
0314IbnActhamKufi.Futuh.Shia003675Vols-ara1 

### ISSUE THREAD

**Issue by rjaques** [OpenITI/Annotation#495]
**LINK:** <paste your link here>
**ISSUE:** Describe issues with the text
Link broken

**RESOLUTION:** Please, propose what should be done with the text

**NOTE:** Please, paste the URI of the text into the header.

**Comment by sohailmerchant** [comment]
Do you mean the link is broken in the app? if yes, here is the link.  
https://raw.githubusercontent.com/OpenITI/0325AH/master/data/0314IbnActhamKufi/0314IbnActhamKufi.Futuh/0314IbnActhamKufi.Futuh.Shia003675Vols-ara1.completed

These links get broken when we change the file name to .completed, inProgress or .mARkdown.  We have a solution for this and will try and implement by Feb.

**Comment by rjaques** [comment]
Yes, that is what I meant. There are quite a few broken. Thanks!
-------- Original message --------From: S Merchant <notifications@github.com> Date: 12/17/19  4:43 PM  (GMT-05:00) To: OpenITI/Annotation <Annotation@noreply.github.com> Cc: rjaques <rjaques@indiana.edu>, Author <author@noreply.github.com> Subject: [External] Re: [OpenITI/Annotation] 0314IbnActhamKufi.Futuh.Shia003675Vols-ara1 (#495) This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.Do you mean the link is broken in the app? if yes, here is the link.
https://raw.githubusercontent.com/OpenITI/0325AH/master/data/0314IbnActhamKufi/0314IbnActhamKufi.Futuh/0314IbnActhamKufi.Futuh.Shia003675Vols-ara1.completed
These links get broken when we change the file name to .completed, inProgress or .mARkdown.  We have a solution for this and will try and implement by Feb.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/OpenITI/Annotation/issues/495?email_source=notifications\u0026email_token=AJQ26PBLVCZ2CKR5XJ7I4ATQZFBXTA5CNFSM4J4BS6N2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHEBVUA#issuecomment-566762192",
"url": "https://github.com/OpenITI/Annotation/issues/495?email_source=notifications\u0026email_token=AJQ26PBLVCZ2CKR5XJ7I4ATQZFBXTA5CNFSM4J4BS6N2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHEBVUA#issuecomment-566762192",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
