### ISSUE TITLE
MISSING PASSAGES: 0300IbnKhurdadhbih.MasalikWaMamalik.Shamela0011800-ara1.completed

### ISSUE THREAD

**Issue by mabarber92** [OpenITI/Annotation#645]
**LINK:** https://upload.wikimedia.org/wikisource/ar/c/c1/%D8%A7%D9%84%D9%85%D8%B3%D8%A7%D9%84%D9%83_%D9%88%D8%A7%D9%84%D9%85%D9%85%D8%A7%D9%84%D9%83_%D9%84%D8%A7%D8%A8%D9%86_%D8%AE%D8%B1%D8%AF%D8%A7%D8%B0%D8%A8%D9%87.pdf
**ISSUE:** Final page of text missing (page 266), remainder of text appears ok.
**RESOLUTION:** Add the lost text from linked pdf.

**NOTE:** Please, paste the URI of the text into the header.

**Comment by hamidrh66** [comment]
Added and reviewed: https://github.com/OpenITI/Annotation/issues/2885
